"""Adicionado o campo update_at

Revision ID: 6d2f93433df5
Revises: 9b34fb7e1c6f
Create Date: 2025-06-21 13:35:07.061636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2f93433df5'
down_revision: Union[str, Sequence[str], None] = '9b34fb7e1c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
