"""Retirando o campo update_at p/ a aula 05

Revision ID: 9de79fc342c1
Revises: 6d2f93433df5
Create Date: 2025-06-21 19:29:25.649283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de79fc342c1'
down_revision: Union[str, Sequence[str], None] = '6d2f93433df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
